# -*- coding: utf-8 -*-
"""
/***************************************************************************

                       EING GML import/export plugin

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-20
        copyright            : (C) 2024 by Tigra Kft.
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QDialog, QMessageBox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'export_plugin_dialog_base.ui'))


class ExportDialog(QDialog, FORM_CLASS):

    def __init__(self, tr, parent=None):
        """Constructor."""
        super(ExportDialog, self).__init__(parent)
        self.tr = tr
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.export_gpkg_path.fileChanged.connect(self.export_gpkg_path_changed)

        # default accept function leválasztása, és saját accept (path validációval) rácsatlakoztatása
        self.button_box.accepted.disconnect(self.accept)
        self.button_box.accepted.connect(self.accept_export)

    def export_gpkg_path_changed(self):
        """ handler to fill gml path based on geopackage path """
        self.export_gml_path.setFilePath(self.export_gpkg_path.filePath().replace(".gpkg", ".gml"))

    def accept_export(self):
        """ Custom accept method to check fields """
        if len(self.export_gpkg_path.filePath()) == 0 or \
           len(self.export_gml_path.filePath()) == 0:
            QMessageBox.critical(None, self.tr("Empty field"),
                                 self.tr("Fill both fields"))
            return

        if not os.path.exists(self.export_gpkg_path.filePath()):
            QMessageBox.critical(None, self.tr("Missing file"),
                                           self.tr("GeoPackage to be exported not found"))
            return
        if os.path.exists(self.export_gml_path.filePath()):
            ans = QMessageBox.question(None, self.tr("Existing file"),
                                 self.tr("GML file already exists, overwrite?"))
            if ans == QMessageBox.No:
                return
        self.accept()
